[package]
name = "basic_usage"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dirs = "6.0.0"
vibrato-rkyv = { path = "../../vibrato" }

[[bin]]
name = "basic_usage"
path = "main.rs"
